### ISSUE TITLE
Unit tests fail with bundled rspec version

### ISSUE THREAD

**Issue by ireneybean** [healthify/fake_idp#36]
```
bundle install
+ bundle install
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using i18n 1.8.3
Using minitest 5.14.1
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using activesupport 5.2.4.3
Using activemodel 5.2.4.3
Using builder 3.2.4
Using bundler 2.1.4
Using coderay 1.1.2
Using diff-lcs 1.2.5
Using dotenv 1.0.2
Using mini_portile2 2.4.0
Using nokogiri 1.10.9
Using ruby-saml 1.11.0
Using systemu 2.6.5
Using macaddr 1.7.1
Using uuid 2.3.8
Using ruby-saml-idp 0.3.2 from https://github.com/lawrencepit/ruby-saml-idp.git (at master@ae53d76)
Using ruby2_keywords 0.0.2
Using mustermann 1.1.1
Using rack 2.2.2
Using rack-protection 2.0.8.1
Using tilt 2.0.10
Using sinatra 2.0.8.1
Using xmlmapper 0.7.3
Using xmlenc 0.7.1
Using fake_idp 0.6.1 from source at `.`
Using method_source 0.9.2
Using pry 0.12.2
Using rspec-support 3.4.1
Using rspec-core 3.4.2
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
Using rspec 3.4.0
Bundle complete! 7 Gemfile dependencies, 36 gems now installed.
Bundled gems are installed into `./vendor`
cp .env.example .env
+ cp .env.example .env

# Do any other automated setup that you need to do here
irene.shaw@OM-C02Z2491LVDQ fake_idp % brake spec
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00007ff653350448>
/Users/irene.shaw/dev/fake_idp/vendor/ruby/2.6.0/gems/rspec-core-3.4.2/lib/rspec/core/rake_task.rb:91:in `define'
/Users/irene.shaw/dev/fake_idp/vendor/ruby/2.6.0/gems/rspec-core-3.4.2/lib/rspec/core/rake_task.rb:71:in `initialize'
/Users/irene.shaw/dev/fake_idp/Rakefile:4:in `new'
/Users/irene.shaw/dev/fake_idp/Rakefile:4:in `<top (required)>'
/Users/irene.shaw/dev/fake_idp/vendor/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/irene.shaw/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/irene.shaw/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

I can submit a pull request to fix this.

**Comment by cbortz** [comment]
Fixed by #37
